# **MÓDULO 13**
# Projeto - Fundamentos da Descoberta de Dados

Nesse projeto trabalharemos com a base de dados de produtos de um supermercado do Chile.
A ideia é que vocês apliquem os conceitos estatísticos vistos no último módulo, mais os conceitos de visualizações de dados através de gráficos e finalizem publicando no seu github!

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

Faça a leitura dos dados do arquivo CSV:


Altere o código abaixo de acordo com seu diretório.

In [2]:
df = pd.read_csv("bases/MODULO7_PROJETO_FINAL_BASE_SUPERMERCADO.csv", delimiter=',')
df.head()

,title,Marca,Preco_Normal,Preco_Desconto,Preco_Anterior,Desconto,Categoria
0,"Pack 12 un, Leche extra proteína 1 L",Loncoleche,19788,0,0,0,lacteos
1,"Pack 12 un, Leche chocolate receta original 1 L",Soprole,18228,0,0,0,lacteos
2,"Pack 12 un, Leche semidescremada chocolate 1 L",Soprole,18228,0,0,0,lacteos
3,"Pack 12 un, Leche semidescremada frutilla 1 L",Soprole,18228,0,0,0,lacteos
4,"Pack 12 un, Leche sin lactosa chocolate 1 L",Loncoleche,17988,0,0,0,lacteos

Os campos do nosso dataframe são:

**Title:** Nome do produto.


**Marca:** A marca do produto.


**Preco_Normal:** O preço em que o produto costuma ser vendido quando não há desconto.


**Preco_Desconto:** O preço vendido após o desconto ser aplicado.


**Preco_Anterior:** Preço em que era comercializado o produto antes do desconto aplicado.


**Desconto:** Total de desconto aplicado.






As colunas que aparecem com valores 0 são para os produtos onde não tivemos descontos aplicados.


As categorias estão em espanhol!

# 1 - Traga a média e a mediana dos preços - coluna Preco_Normal - por categoria de produto.
# Identifique as categorias que parecem ter um valor de média abaixo ou acima da mediana.

In [3]:
#Seu código aqui para a média
media = df.groupby("Categoria")["Preco_Normal"].mean().round(2)
media

Categoria
belleza-y-cuidado-personal    1783.56
comidas-preparadas            3095.04
congelados                    2108.04
frutas                        1724.47
instantaneos-y-sopas           765.49
lacteos                       2385.22
verduras                      1343.30
Name: Preco_Normal, dtype: float64

In [4]:
#Seu código aqui para a mediana
mediana = df.groupby("Categoria")["Preco_Normal"].median().round(2)
mediana

Categoria
belleza-y-cuidado-personal    1569.0
comidas-preparadas            3290.0
congelados                    1519.0
frutas                        1195.0
instantaneos-y-sopas           439.0
lacteos                        989.0
verduras                      1180.0
Name: Preco_Normal, dtype: float64

Digite aqui as categorias:

In [5]:
acima = " ".join(media[media > mediana].index)
abaixo = " ".join(media[media < mediana].index)
print(f"Categorias com médias maiores que a mediana: {acima}.")
print(f"Categorias com médias menores que a mediana: {abaixo}.")

Categorias com médias maiores que a mediana: belleza-y-cuidado-personal congelados frutas instantaneos-y-sopas lacteos verduras.
Categorias com médias menores que a mediana: comidas-preparadas.

# 2 - Traga o desvio padrão por categoria de produto.
# Qual o comportamento da média e mediana nas categorias com maior desvio?

In [6]:
#Seu código aqui
desvio = df.groupby("Categoria")["Preco_Normal"].std().sort_values(ascending=False)
desvio

Categoria
lacteos                       3925.816164
belleza-y-cuidado-personal    2210.041719
congelados                    2111.539896
comidas-preparadas            2019.911428
frutas                        1639.151114
instantaneos-y-sopas          1170.232869
verduras                      1012.699625
Name: Preco_Normal, dtype: float64

In [7]:
estat = pd.DataFrame(columns=["Categoria", "Média", "Mediana", "Desvio"])
estat["Categoria"] = desvio.index.sort_values()
estat["Média"] = estat["Categoria"].map(media)
estat["Mediana"] = estat["Categoria"].map(mediana)
estat["Desvio"] = estat["Categoria"].map(desvio)
estat

                    Categoria    Média  Mediana       Desvio
0  belleza-y-cuidado-personal  1783.56   1569.0  2210.041719
1          comidas-preparadas  3095.04   3290.0  2019.911428
2                  congelados  2108.04   1519.0  2111.539896
3                      frutas  1724.47   1195.0  1639.151114
4        instantaneos-y-sopas   765.49    439.0  1170.232869
5                     lacteos  2385.22    989.0  3925.816164
6                    verduras  1343.30   1180.0  1012.699625

In [8]:
estat.loc[:, "CV"] = (estat["Desvio"] / estat["Média"]).round(4)
estat

                    Categoria    Média  Mediana       Desvio      CV
0  belleza-y-cuidado-personal  1783.56   1569.0  2210.041719  1.2391
1          comidas-preparadas  3095.04   3290.0  2019.911428  0.6526
2                  congelados  2108.04   1519.0  2111.539896  1.0017
3                      frutas  1724.47   1195.0  1639.151114  0.9505
4        instantaneos-y-sopas   765.49    439.0  1170.232869  1.5287
5                     lacteos  2385.22    989.0  3925.816164  1.6459
6                    verduras  1343.30   1180.0  1012.699625  0.7539

Digite nesse campo o comportamento que você identificou.

Produtos das categorias: 
belleza-y-cuidado-personal, 
instantaneos-y-sopas, 
lacteos, 
têm o desvio padrão muito alto em relação a média e mediana, é provável a presença de outliers nestas categorias de produtos.

---

Este método foi feito apenas para exibir os gráficos no navegador, pois o VSCode não estava conseguindo exibir.

In [9]:
import os
import webbrowser


def plot_to_html(fig, name: str):
    caminho_arquivo = os.path.abspath(name)
    fig.write_html(caminho_arquivo)
    
    comando_incognito = "firefox --private-window %s" 
    browser = webbrowser.get(comando_incognito)
    
    browser.open(caminho_arquivo)

# 3 - Plot um boxplot da distribuição do Preco_Normal para a categoria que você identificou que tem o maior desvio padrão. Como é a distribuição desses dados segundo o boxplot? Você identifica muitos outliers?

Dica: Para trazer apenas os dados da categoria que você deseja você pode usar o df.loc[df['Categoria'] == 'CATEGORIA ESCOLHIDA'

In [ ]:
#Seu código aqui
categorias = "belleza-y-cuidado-personal,instantaneos-y-sopas,lacteos"
cat_interesse = df.loc[df["Categoria"].isin(categorias.split(","))]

fig = px.box(
    cat_interesse, 
    x="Categoria", 
    y="Preco_Normal", 
    title="Categorias com alto Desvio Padrão | Presença de Outliers", 
    color="Categoria", 
    color_discrete_sequence=["#ff033e", "#9966cc", "#ffbf00"]
)
plot_to_html(fig, "box_preco.html")

# 4 - Plote um gráfico de barras onde temos a média de descontos por categoria.

In [11]:
# Seu código aqui
desc_cat = df.groupby("Categoria")["Desconto"].mean().reset_index()
desc_cat = desc_cat.sort_values("Desconto", ascending=False)
fig = px.bar(
    desc_cat, 
    x="Categoria", 
    y="Desconto", 
    title="Média de Descontos por Categoria", 
    color="Categoria", 
)
plot_to_html(fig, "descontos.html")

# 5 - Plote um gráfico de mapa interativo agrupando os dados por categoria, marca e trazendo a média de desconto.

In [12]:
# Seu código aqui
fig = px.density_heatmap(
    df, 
    x="Categoria", 
    y="Marca", 
    z="Desconto", 
    histfunc="avg", 
    color_continuous_scale=["#f4bbff", "#800020"], 
    title="Média de Desconto por Categoria e Marca"
)
plot_to_html(fig, "heatmap_desconto.html")

---